version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '18:00'
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 100
    commit-message:
      prefix: 'chore(pnpm deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'pnpm'
    assignees:
      - 'Xayrulloh'
    reviewers:
      - 'Xayrulloh'
    groups: {}
