name: Production Deployment

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ghcr.io/xayrulloh/family-tree-api:stable
  DEPLOY_PATH: /opt/family-tree/production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build API
        run: npx nx build api --prod

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/xayrulloh/family-tree-api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deploy directory
        run: mkdir -p deploy

      - name: Fetch Infisical secrets
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: ${{ secrets.INFISICAL_PROJECT_ID }}
          env-slug: prod
          export-type: file
          file-output-path: "/deploy/.env"
          include-imports: true
          recursive: true

      - name: Add runtime vars and prepare files
        run: |
          echo "DOCKER_IMAGE=${{ env.IMAGE_TAG }}" >> deploy/.env
          cp apps/api/docker-compose.yml deploy/docker-compose.yml

      - name: Clean up old files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            sudo rm -f ${{ env.DEPLOY_PATH }}/.env ${{ env.DEPLOY_PATH }}/docker-compose.yml

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "deploy/.env,deploy/docker-compose.yml"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            bash -c "
            set -e

            # Change to deploy directory
            cd ${{ env.DEPLOY_PATH }}

            echo 'Logging into GHCR...'
            echo '${{ secrets.GHP_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo 'Pulling latest image...'
            docker compose pull

            echo 'Restarting containers...'
            docker compose up -d --remove-orphans

            echo 'Cleaning unused images...'
            docker image prune -f

            echo 'Deployment complete ðŸŽ‰'
            "